nelmio_api_doc:
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
        internal:
            with_attribute: true
        public:
            with_attribute: true
