version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-pedidos-app
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "postgresql://symfony_user:senha_segura@db:5432/sistema_pedidos"
      MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@localhost:5672/%2f/messages"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    expose:
      - 9000
    
  db:
    image: postgres:15
    container_name: sistema-pedidos-db
    restart: always
    environment:
      POSTGRES_DB: sistema_pedidos
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: senha_segura
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "symfony_user", "-d", "sistema_pedidos"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  nginx:
    image: nginx:latest
    container_name: sistema-pedidos-nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
