categoria_api:
    resource: './routes/categoria_routes.yaml'

cliente_api:
    resource: './routes/cliente_routes.yaml'

pedido_api:
    resource: './routes/pedido_routes.yaml'

produto_api:
    resource: './routes/produto_routes.yaml'