services:

    App\External\Database:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    App\Api\CategoriaApi:
        arguments:
            $db_connection: '@App\External\Database'
        public: true

    App\Api\ClienteApi:
        arguments:
            $db_connection: '@App\External\Database'
        public: true

    App\Api\ProdutoApi:
        arguments:
            $db_connection: '@App\External\Database'
        public: true

    App\Api\PedidoApi:
        arguments:
            $db_connection: '@App\External\Database'
        public: true