apiVersion: v1
kind: Service
metadata:
  name: sistema-pedidos-service
spec:
  type: NodePort               
  selector:
    app: sistema-pedidos-app
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 9000        
      nodePort: 30080       
