apiVersion: v1
kind: Service
metadata:
  name: sistema-pedidos-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer               
  selector:
    app: sistema-pedidos-app
  ports:
      - port: 443                
        targetPort: 9000        
