apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-pedidos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistema-pedidos-app
  template:
    metadata:
      labels:
        app: sistema-pedidos-app
    spec:
      containers:
        - name: sistema-pedidos-app
          image: edwinkimura/sistema-pedidos-app:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: dbname
          ports:
            - containerPort: 9000
