apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        error_log   /var/log/nginx/error.log;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        server {
            listen       80;
            server_name  localhost;

            root /var/www/html/public;
            index index.php index.html index.htm;

            location / {
                try_files $uri /index.php$is_args$args;
            }
        
            location ~ ^/index\.php(/|$) {
                fastcgi_pass  sistema-pedidos-service:80; 
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php; 
                include fastcgi_params;
            }
    
            location ~ \.php$ {
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param REQUEST_METHOD $request_method;
                fastcgi_param QUERY_STRING $query_string;
                fastcgi_param CONTENT_TYPE $content_type;
                fastcgi_param CONTENT_LENGTH $content_length;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_param REQUEST_URI $request_uri;
                fastcgi_param DOCUMENT_URI $document_uri;
                fastcgi_param DOCUMENT_ROOT $document_root;
                fastcgi_param SERVER_PROTOCOL $server_protocol;
                fastcgi_param HTTPS $https if_not_empty;
                fastcgi_param GATEWAY_INTERFACE CGI/1.1;
                fastcgi_param SERVER_SOFTWARE nginx/$nginx_version;
                fastcgi_param REMOTE_ADDR $remote_addr;
                fastcgi_param REMOTE_PORT $remote_port;
                fastcgi_param SERVER_ADDR $server_addr;
                fastcgi_param SERVER_PORT $server_port;
                fastcgi_param SERVER_NAME $server_name;
                fastcgi_pass sistema-pedidos-service:80;
                fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
                include fastcgi_params;
            }

            error_log /var/log/nginx/error.log;
            access_log /var/log/nginx/access.log;
        }
    }
